# Generated by Django 5.2.4 on 2025-08-31 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketapi", "0002_document_uploaded_by_project_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
    ]
