# Generated by Django 5.2.4 on 2025-09-02 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketapi", "0003_remove_document_uploaded_by_remove_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with +92 and contain 13 digits",
                        regex="^\\+92\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "manager"),
                    ("DEVELOPER", "developer"),
                    ("QA", "qa"),
                    ("DESIGNER", "designer"),
                ],
                default="manager",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "open"),
                    ("WORKING", "working"),
                    ("REVIEW", "review"),
                    ("WAITING_QA", "waiting_qa"),
                    ("AWAITING_RELEASE", "awaiting_release"),
                    ("CLOSED", "closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "created"),
                    ("UPDATED", "updated"),
                    ("DELETED", "deleted"),
                ],
                max_length=20,
            ),
        ),
    ]
